[package]
name = "mypasswd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "7.0.0"
rust-crypto = "^0.2"
rand = "^0.3"
dirs = "4.0.0"
